version: 2
updates:
  # Nuget dependencies
  - package-ecosystem: "nuget"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "23:15"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "23:15"
